#! /usr/bin/env python
"""
Create an IETF WG repository for an I-D

Flags:
    --wg WGNAME
    --doc DOCNAME (removes /draft-/ /ietf-/ /$WGNAME-/ prefixes; any others?)
    --editor GH_ID (can be repeated, must be at least once)
    --n name:pass Github login credentials

Creates a repository draft-$WGNAME-$DOCNAME within the ietf-wg-$WGNAME
organization.  Populates it with various templated stuff.
"""

import getopt, sys

# Set defaults
WGNAME = None
DOCNAME = None
EDITORS = []
NAMEPASS = None

# Parse JCL.
try:
    opts, args = getopt.getopt(sys.argv[1:], "hw:d:e:n:",
                              ["wg=", "doc=", "editor=", "np="])
except getopt.GetoptError as err:
    print str(err)
    raise SystemExit
for o,a in opts:
    if o == '-h':
        print __doc__
        raise SystemExit
    if o in ("-w", "--wg"):
        WGNAME = a
    elif o in ("-d", "--doc"):
        DOCNAME = a
    elif o in ("-e", "--editor"):
        EDITORS += [ a ]
    elsif o in ("-n", "--np"):
        NAMEPASS = a
    else:
        assert False, "Unhandled option: " + o

# Verify flag syntax.
if not WGNAME:
    raise SystemExit("-w/--wg flag required")
if not DOCNAME:
    raise SystemExit("-d/--doc flag required")
if len(EDITORS) == 0:
    raise SystemExit( "-e/--editor flag required")

# Login
G,USER = UTILS.gh_login(NAMEPASS)

# Verify user names
if not UTILS.verify_users(G, EDITORS):
    raise SystemExit("Missing GH accounts");

# See if organization exists.
WGNAME = UTILS.fix_wg_name(WGNAME)
DOC="draft-" + WGNAME + "-" + DOCNAME
ORG = 'ietf-wg-' + WGNAME
if not UTILS.org_exists(G, ORG):
    raise SystemExit("Organization not found; try mk-ietf-wg")

# Create an editors team and populate it
editors = o.create_team(DOC)
editors.add_membership(USER)
for e in EDITORS:
    editors.add_membership(e)

# Create repository draft-$WGNAME-$DOCNAME in ietf-wg-$WGNAME
repo = o.create_repo(DOC,
        description="Repository for " + DOC + " draft",
        has_issues=True, # Probably the default, but this is funny
        team_id=editors.id
        )

# Create common labels
repo.create_label("editorial", "green")
repo.create_label("design", "pink")
repo.create_label("parked", "yellow")

# Add Martin's I-D tools (as a submodule)
# Run the script to populate CONTRIBUTING etc
