#! /usr/bin/env python
"""
Create an IETF WG repository for an I-D

Flags:
    --wg WGNAME
    --doc DOCNAME (removes /draft-/ /ietf-/ /$WGNAME-/ prefixes; any others?)
    --editor GH_ID (can be repeated, must be at least once)

Creates a repository draft-$WGNAME-$DOCNAME within the ietf-wg-$WGNAME organization.

Creates the common issues "editorial" and "design" (any others, like "parked"?)

Creates a $DOCNAME team within the organization that has the editors and
owners as members of that repo.  Maybe editors is optional?

Adds Martin's I-D tools as a submodule, runs the initial script to populate
contributing, etc.

Edits the Makefile as needed, to populate all $WGNAME related URL's
"""

import getopt, sys

# Set defaults
WGNAME = None
DOCNAME = None
EDITOR = []

# Parse JCL.
try:
    opts, args = getopt.getopt(sys.argv[1:], "hw:d:e:",
                              ["wg=", "doc=", "editor="])
except getopt.GetoptError as err:
    print str(err)
    raise SystemExit
for o,a in opts:
    if o == '-h':
        print __doc__
        raise SystemExit
    if o in ("-w", "--wg"):
        WGNAME = a
    elif o in ("-d", "--doc"):
        DOCNAME = a
    elif o in ("-e", "--editor"):
        EDITOR += [ a ]
    else:
        assert False, "Unhandled option"

# Verify flag syntax.
if not WGNAME:
    raise SystemExit("-w/--wg flag required")
if not DOCNAME:
    raise SystemExit("-d/--doc flag required")
if len(EDITOR) == 0:
    raise SystemExit( "-e/--editor flag required")
